const COMMENTS_LIST = 'COMMENTS_LIST';
const COMMENTS_LIST_REQUEST_START = 'COMMENTS_LIST_REQUEST_START';
const COMMENTS_LIST_REQUEST_FAIL = 'COMMENTS_LIST_REQUEST_FAIL'
const COMMENTS_CREATE = 'COMMENTS_CREATE'
const COMMENTS_DELETE = 'COMMENTS_DELETE'
const COMMENT_EDIT = 'COMMENT_EDIT'


const types = {
    COMMENTS_LIST,
    COMMENTS_LIST_REQUEST_START,
    COMMENTS_LIST_REQUEST_FAIL,
    COMMENTS_CREATE,
    COMMENTS_DELETE,
    COMMENT_EDIT
    
};

export default types;