const LIKES_LIST = 'LIKES_LIST';
const LIKES_LIST_REQUEST_START = 'LIKES_LIST_REQUEST_START';
const LIKES_LIST_REQUEST_FAIL = 'LIKES_LIST_REQUEST_FAIL'
const LIKES_PLUS = 'LIKES_PLUS'
const LIKES_MINUS = 'LIKES_MINUS'
const LIKES_CREATE = 'LIKES_CREATE'


const types = {
    LIKES_LIST,
    LIKES_LIST_REQUEST_START,
    LIKES_LIST_REQUEST_FAIL,
    LIKES_CREATE,
    LIKES_PLUS,
    LIKES_MINUS,
    
};

export default types;