const USER_LIST = 'USER_LIST';
const USER_LIST_REQUEST_START = 'USER_LIST_REQUEST_START';
const USER_LIST_REQUEST_FAIL = 'USER_LIST_REQUEST_FAIL'
const USER_CREATE = 'USER_CREATE'
const USER_DELETE = 'USER_DELETE'
const USER_LOGIN = 'USER_LOGIN'


const types = {
    USER_LIST,
    USER_LIST_REQUEST_START,
    USER_LIST_REQUEST_FAIL,
    USER_CREATE,
    USER_DELETE,
    USER_LOGIN
    
};

export default types;