const POST_LIST = 'POST_LIST';
const POST_LIST_REQUEST_START = 'POST_LIST_REQUEST_START';
const POST_LIST_REQUEST_FAIL = 'POST_LIST_REQUEST_FAIL'
const POST_CREATE = 'POST_CREATE'
const POST_DELETE = 'POST_DELETE'


const types = {
    POST_LIST,
    POST_LIST_REQUEST_START,
    POST_LIST_REQUEST_FAIL,
    POST_CREATE,
    POST_DELETE,
    
};

export default types;